spring:
  application:
    name: gestao-tcc
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/gestaotcc_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
