spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestaotcc_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false